apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: express-app-5
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/johnmoreno-buildah-assigment-express.git
    - name: image-repo
      value: quay.io/johnmorenoing/express-app
  pipelineRef:
    name: express-buildah-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
            - ReadWriteOnce